FROM ubuntu
FROM zhengyixu/riscv-devkit-2

MAINTAINER Zhengyi Xu (zhengyixu) <zhengyi123@gmail.com>

ENV RISCV /opt/riscv
ENV NUMJOBS 1
ENV PATH $RISCV/bin:$PATH

WORKDIR /tmp
RUN set -x && \
    mkdir linux-4.1.y && cd linux-4.1.y && git init && \
    git remote add origin https://github.com/riscv/riscv-linux.git && \
    git fetch && git checkout -b linux origin/linux-4.1.y-riscv && \
    make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- defconfig && \
    make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- vmlinux && \
    mv vmlinux $RISCV && \
    rm -rf /tmp/*
