FROM ubuntu

MAINTAINER Zhengyi Xu (zhengyixu) <zhengyi123@gmail.com>

RUN apt-get update && apt-get install --no-install-recommends -y \
    apt-utils \
    autoconf \
    automake \
    autotools-dev \
    bash-completion \
    bc \
    bison \
    build-essential \
    curl \
    flex \
    gawk \
    git \
    gperf \
    libmpc-dev \
    libmpfr-dev \
    libgmp-dev \
    libtool \
    ncurses-dev \
    patchutils \
    texinfo \ 
    vim-nox \
		&& apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

